# syntax=docker/dockerfile:1.7
# Development Dockerfile for Next.js
FROM node:22-alpine
RUN corepack enable
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on lockfile present
COPY package.json package-lock.json* pnpm-lock.yaml* yarn.lock* ./
RUN --mount=type=cache,target=/root/.npm \
    --mount=type=cache,target=/root/.pnpm-store \
    --mount=type=cache,target=/usr/local/share/.cache/yarn \
    if [ -f pnpm-lock.yaml ]; then pnpm i --frozen-lockfile; \
    elif [ -f yarn.lock ]; then yarn install --frozen-lockfile; \
    elif [ -f package-lock.json ]; then npm ci; \
    else echo "Lockfile not found." && exit 1; fi

# Source will be bind-mounted in compose
COPY . .

EXPOSE 4000 9229
ENV NODE_ENV=development
ENV PORT=4000

CMD if [ -f pnpm-lock.yaml ]; then pnpm dev -p $PORT; \
  elif [ -f yarn.lock ]; then yarn dev -p $PORT; \
  elif [ -f package-lock.json ]; then npm run dev -- -p $PORT; \
  else echo "Lockfile not found." && exit 1; fi
