type PhaseTemplateInput = {
  phase: number;
  format: "mdx" | "json";
};

export function phaseTemplate({ phase, format }: PhaseTemplateInput): string {
  if (format === "json") {
    return (
      JSON.stringify(
        {
          $schema: "https://cursor.directory/schema.json",
          phase,
          title: `Phase ${phase}`,
          goal: `Complete Phase ${phase} of the NextForge implementation`,
          checklist: [
            "Review phase requirements",
            "Gather necessary context",
            "Implement changes",
            "Run tests",
            "Update documentation",
          ],
          inputs: ["Requirements document", "Previous phase deliverables", "Codebase context"],
          deliverables: [
            "Implemented features",
            "Test coverage",
            "Documentation updates",
            "Code review",
          ],
          steps: [
            "Review the requirements for this phase",
            "Implement the necessary changes",
            "Run tests to verify correctness",
            "Update documentation",
          ],
          validation: [
            "All tests pass",
            "Build completes without errors",
            "Generated files follow conventions",
            "Documentation is updated",
          ],
        },
        null,
        2
      ) + "\n"
    );
  }

  // MDX format
  return `---
phase: ${phase}
title: Phase ${phase}
tags: [cursor, phase]
---

<!--
  Phase ${phase} Implementation Guide

  How to use:
  1. Read through the checklist
  2. Paste relevant code context where marked {{selection}}
  3. Use this as a prompt in Cursor
  4. Follow the validation checklist

  File generated by NextForge CLI
-->

# Phase ${phase}

## Goal

Complete Phase ${phase} of the NextForge implementation.

## Checklist

- [ ] Review phase requirements
- [ ] Gather necessary context
- [ ] Implement changes
- [ ] Run tests
- [ ] Update documentation

## Inputs

- Requirements document
- Previous phase deliverables
- Codebase context {{selection}}

## Deliverables

- Implemented features
- Test coverage
- Documentation updates
- Code review

## Steps

1. Review the requirements for this phase
2. Implement the necessary changes
3. Run tests to verify correctness
4. Update documentation

## Cursor Prompt Example

\`\`\`
Implement Phase ${phase} for NextForge:

Context:
- Working in a Next.js + TypeScript project
- Using NextForge CLI conventions
- Target: app directory structure

{{selection}}

Tasks:
- [ ] Scaffold required files
- [ ] Add necessary configuration
- [ ] Write integration tests
- [ ] Verify build passes

Available flags:
--force         Overwrite existing files
\`\`\`

## Validation

- [ ] All tests pass
- [ ] Build completes without errors
- [ ] Generated files follow conventions
- [ ] Documentation is updated
- [ ] Code reviewed and approved
`;
}
