type RulesTemplateInput = {
  name: string;
  format: "mdx" | "json";
};

export function rulesTemplate({ name, format }: RulesTemplateInput): string {
  if (format === "json") {
    return (
      JSON.stringify(
        {
          $schema: "https://schemas.nextforge.dev/cursor-rules.v1.json",
          name,
          version: 1,
          scopes: ["components", "pages", "api"],
          rules: [
            {
              id: "naming",
              text: "Use PascalCase for components and folders under /app/components/*",
            },
            {
              id: "tests",
              text: "When --with-tests is specified, create *.test.tsx colocated with the component",
            },
            {
              id: "imports",
              text: "Use ESM imports and avoid default exports for better tree-shaking",
            },
            {
              id: "types",
              text: "Add JSDoc comments for public APIs and use TypeScript strict mode",
            },
          ],
          dos: [
            "Keep functions small and focused",
            "Use descriptive variable names",
            "Add comments for non-obvious code",
            "Test edge cases",
          ],
          donts: [
            "Don't modify generated files directly",
            "Don't skip error handling",
            "Don't use any types",
            "Don't commit commented-out code",
          ],
        },
        null,
        2
      ) + "\n"
    );
  }

  // MDX format
  return `---
type: rules
name: ${name}
title: ${name}
version: 1
scopes: [components, pages, api]
tags: [cursor, rules]
---

<!--
  Cursor Rules for ${name}

  How to use:
  1. Open Cursor Settings → Rules
  2. Add this file or paste its contents
  3. Pin to your workspace for active enforcement

  File generated by NextForge CLI
-->

# Cursor Rules — ${name}

## Purpose

Define rules and conventions for ${name} to guide Cursor AI during development.

## Rules

### Naming
Use PascalCase for components and folders under \`/app/components/*\`

### Tests
When \`--with-tests\` is specified, create \`*.test.tsx\` colocated with the component

### Imports
Use ESM imports and avoid default exports for better tree-shaking

### Types
Add JSDoc comments for public APIs and use TypeScript strict mode

## Guidelines

- Follow existing code patterns
- Use ESM imports
- Add JSDoc comments for public APIs
- Write tests alongside implementation

## Conventions

- Use TypeScript for type safety
- Follow NextForge project structure
- Include comprehensive error handling
- Document complex logic

## Do

✅ Keep functions small and focused
✅ Use descriptive variable names
✅ Add comments for non-obvious code
✅ Test edge cases

## Don't

❌ Don't modify generated files directly
❌ Don't skip error handling
❌ Don't use \`any\` types
❌ Don't commit commented-out code

## File Ownership

This rules file is version-controlled and owned by the team. Updates should go through code review.

## Example Prompt

\`\`\`yaml
task: implement ${name}
context:
  - Use NextForge conventions
  - Follow TypeScript best practices
  - Include tests
output:
  - Component implementation
  - Test coverage
  - Documentation
\`\`\`
`;
}
