type RulesTemplateInput = {
  name: string;
  format: "mdx" | "json";
};

export function rulesTemplate({ name, format }: RulesTemplateInput): string {
  if (format === "json") {
    return (
      JSON.stringify(
        {
          $schema: "https://cursor.directory/schema.json",
          name,
          description: `Cursor AI rules for ${name}`,
          guidelines: [
            "Follow existing code patterns",
            "Use ESM imports",
            "Add JSDoc comments for public APIs",
            "Write tests alongside implementation",
          ],
          conventions: [
            "Use TypeScript for type safety",
            "Follow NextForge project structure",
            "Include comprehensive error handling",
            "Document complex logic",
          ],
          dos: [
            "Keep functions small and focused",
            "Use descriptive variable names",
            "Add comments for non-obvious code",
            "Test edge cases",
          ],
          donts: [
            "Don't modify generated files directly",
            "Don't skip error handling",
            "Don't use any types",
            "Don't commit commented-out code",
          ],
          examples: [],
        },
        null,
        2
      ) + "\n"
    );
  }

  // MDX format
  return `---
title: ${name}
tags: [cursor, rules]
description: Cursor AI rules for ${name}
---

<!--
  Cursor Rules for ${name}

  How to use:
  1. Open Cursor Settings → Rules
  2. Add this file or paste its contents
  3. Pin to your workspace for active enforcement

  File generated by NextForge CLI
-->

# Cursor Rules — ${name}

## Purpose

Define rules and conventions for ${name} to guide Cursor AI during development.

## Guidelines

- Follow existing code patterns
- Use ESM imports
- Add JSDoc comments for public APIs
- Write tests alongside implementation

## Conventions

- Use TypeScript for type safety
- Follow NextForge project structure
- Include comprehensive error handling
- Document complex logic

## Do

✅ Keep functions small and focused
✅ Use descriptive variable names
✅ Add comments for non-obvious code
✅ Test edge cases

## Don't

❌ Don't modify generated files directly
❌ Don't skip error handling
❌ Don't use \`any\` types
❌ Don't commit commented-out code

## File Ownership

This rules file is version-controlled and owned by the team. Updates should go through code review.

## Example Prompt

\`\`\`yaml
task: implement ${name}
context:
  - Use NextForge conventions
  - Follow TypeScript best practices
  - Include tests
output:
  - Component implementation
  - Test coverage
  - Documentation
\`\`\`
`;
}
